### ISSUE TITLE
Request for  a working example

### ISSUE THREAD

**Issue by thaingo** [Neloop/jaclp#1]
Hi @Neloop,

It would be a great help if you could provide a working example using your library for ABAC so that we can have a clear understanding of it. 

Could you please do that?

Thanks,
Thai

**Comment by Neloop** [comment]
Hi,
yes that would be possible. I would like to make working sample project and also something like tutorial, it is on my mind for some time. But for now, working example project with Spring integration should and has to be enough. I will try to get onto it as soon as possible.

Note that somewhat basic samples can be found in tests, look at [DemoPermissionsService](https://github.com/Neloop/jaclp/blob/master/src/test/java/cz/polankam/security/acl/test_utils/DemoPermissionsService.java) class.

Thanks for the interest in the library!

**Comment by thaingo** [comment]
Thanks @Neloop for your response and looking forward to working example with Spring integration.

I did look into In the [DemoPermissionsService](https://github.com/Neloop/jaclp/blob/master/src/test/java/cz/polankam/security/acl/test_utils/DemoPermissionsService.java), I do need some more guidance. 
I would like to implement abac for a persistent resource. Take the [DemoGroup](https://github.com/Neloop/jaclp/blob/master/src/test/java/cz/polankam/security/acl/test_utils/DemoGroup.java) as a starting point but now I want it to be a JPA entity.
How would the [GroupDemoRepository](https://github.com/Neloop/jaclp/blob/master/src/test/java/cz/polankam/security/acl/test_utils/DemoGroupRepository.java) be implemented using both `IResourceRepository` and `JpaRepository` of Spring JPA?

**Comment by Neloop** [comment]
Hi,
I think the example project with full-fledged Spring Boot, JPA and Security integration could be done on this weekend.

But implementing both interfaces should be very straight forward, `IResourceRepository` is intentionally designed to have exactly the same methods as `JpaRepository`, therefore, implementation of both interfaces is easy and could look something like this

```
public interface GroupRepository extends JpaRepository<Group, Long>,
        IResourceRepository<Group, Long> {

    Optional<Group> findByName(String name);
}
```

**Comment by Neloop** [comment]
Hi,
I am really sorry it took so long, I kind of forget about that.
But today I sat down and implemented example project which should be better demonstration of how to use the library. The project resides here [jaclp-demo](https://github.com/Neloop/jaclp-demo).

Please note there is new release of `jaclp` library, because of some problems with transactions in `2.0` version. The new version is `2.1` and should be available shortly in maven central.

Best regards, Martin

**Comment by thaingo** [comment]
Awesome and thanks for great work.
